"""Resource Agent for generating learning resources."""
from typing import Any, Dict

from app.agents.base import BaseAgent, AgentResponse


class ResourceAgent(BaseAgent):
    """Agent responsible for generating learning resources."""

    def __init__(self):
        super().__init__("ResourceAgent")

    def _build_system_prompt(self) -> str:
        return """You are the Resource Agent, an expert at creating and curating educational content.

Your task is to generate high-quality learning resources based on:
1. The learning stage and its objectives
2. Resource type (video, article, exercise, quiz, project)
3. Topic and difficulty level
4. User's learning style preferences

Generate resources that are:
- Relevant to the learning objectives
- Appropriately challenging
- Varied in format to maintain engagement
- Practical and applicable

Each resource should include:
- Clear title and description
- Content in the specified format
- Metadata (tags, difficulty, estimated time)
- Quality indicators"""

    async def process(self, input_data: Dict[str, Any]) -> AgentResponse:
        """Generate learning resources."""
        try:
            path_stage_id = input_data.get("path_stage_id")
            resource_type = input_data.get("resource_type", "article")
            topic = input_data.get("topic", "")
            difficulty = input_data.get("difficulty", "intermediate")
            count = input_data.get("count", 1)

            if not topic:
                return AgentResponse(success=False, error="topic is required")

            prompt = f"""Generate {count} {resource_type} resource(s) for the following specifications:

Topic: {topic}
Difficulty: {difficulty}
Resource Type: {resource_type}

Learning Objectives to address:
{input_data.get('objectives', 'General learning content')}

Please provide resources that are:
1. Engaging and educational
2. Appropriate for the difficulty level
3. Focused on the specified topic
4. Varied in approach within the resource type

For each resource provide:
- Title
- Description
- Full content
- Tags
- Estimated completion time (in minutes)
- Any prerequisites"""

            messages = self._create_messages(self._build_system_prompt(), prompt)
            raw_output = await self._generate_response(messages)

            resources = self._parse_resource_output(raw_output, resource_type)

            return AgentResponse(
                success=True,
                data={"resources": resources, "count": len(resources)},
                raw_output=raw_output,
                metadata={"agent": self.agent_name, "resource_type": resource_type},
            )

        except Exception as e:
            return AgentResponse(success=False, error=str(e))

    def _parse_resource_output(self, raw_output: str, resource_type: str) -> list:
        """Parse LLM output into structured resource data."""
        # Simplified - in production use structured outputs
        return [{
            "title": f"Generated {resource_type}",
            "description": "Resource generated by Resource Agent",
            "resource_type": resource_type,
            "content": raw_output,
            "content_format": "markdown",
            "tags": ["generated"],
            "difficulty_level": "intermediate",
            "estimated_minutes": 30,
        }]
